version: '3.9'

services:
    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./backend/src:/var/www
    frontend:
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        volumes:
            - ./frontend/breeze-next:/app
        command: 'yarn build'
        ports:
            - "3000:3000"
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            MYSQL_DATABASE: spa-crm
            MYSQL_ROOT_PASSWORD: password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        ports:
            - "8836:80"
        volumes:
            - /sessions
volumes:
    mysql-volume: