version: '3.9'

services:
    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./backend/src:/var/www
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - mysql-volume:/var/lib/mysql
        environment:
            MYSQL_DATABASE: sps-crm
            MYSQL_ROOT_PASSWORD: password
volumes:
    mysql-volume: